### ISSUE TITLE
Problems with Chef 13

### ISSUE THREAD

**Issue by truck0321** [hopshadoop/ndb-chef#5]
I'm getting the below error in Chef kitchen with the default kitchen yaml file.  

`       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/kagent/attributes/default.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `kagent' for #<Chef::Node::VividMash:0x0000000315b7d0>

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/kagent/attributes/default.rb:4:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/kagent/attributes/default.rb:

         1:  #node.default.hadoop.version                = "2.4.0"
         2:
         3:  # Default values for configuration parameters
         4>> default.kagent.version                = "0.1.0"
         5:  default.kagent.user                   = "kagent"
         6:  default.kagent.group                  = node.kagent.user
         7:  default.kagent.certs_group            = "certs"
         8:  default.kagent.dir                    = "/var/lib"
         9:  default.kagent.base_dir               = "#{node.kagent.dir}/kagent"
        10:  default.kagent.home                   = "#{node.kagent.dir}/kagent-#{node.kagent.version}"
        11:
        12:  default.kagent.enabled                = "true"
        13:

       System Info:
       ------------
       chef_version=13.1.31
       platform=centos
       platform_version=7.3.1611
       ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
       program_name=chef-client worker: ppid=3788;start=21:06:34;
       executable=/opt/chef/bin/chef-client
`

**Comment by jimdowling** [comment]
Yes, we are aware that we need to update the nicer "node.kagent.XX" to "node['kagent']['XX'] syntax. It's in the near term roadmap -hasn't been done yet, as we use www.karamel.io to orchestrate chef, and it uses 12.X chef-solo.

**Comment by truck0321** [comment]
Thanks,  I realize supporting Chef 13 is a little premature.
